version: '3.8'
services:
  api:
    build: ./
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./src:/main
      - D:/PisCourse/backend/course/node_modules:/app/node_modules
  client:
    build: ../../frontend
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ../frontend/src:/index
      - D:/PisCourse/frontend/node_modules:/app/node_modules
    stdin_open: true
    tty: true
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: LOL123321lol
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
